# Generated by Django 5.2.7 on 2025-11-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('Collection1')                  
        """, """
            DELETE FROM store_collection
            WHERE title='Collection1'
        """)
    ]
